catalogMode: prefer

ignoreWorkspaceRootCheck: true

registry: https://registry.npmmirror.com

shamefullyHoist: true

shellEmulator: true

catalogs:
  dev:
    '@lincy/unocss-base-config': ^2.4.1
    consola: ^3.4.2
    mockjs: ^1.1.0
    postcss-px-to-viewport-8-plugin: ^1.2.5
    sass: ^1.97.2
    simple-git-hooks: ^2.13.1
    stylelint: ^16.26.1
    typescript: ^5.9.3
    vite: ^7.3.1
    vue-tsc: ^3.2.2

  icons:
    '@iconify-json/carbon': ^1.2.16
    '@iconify-json/twemoji': ^1.2.5

  lint:
    '@lincy/eslint-config': ^6.3.3
    '@lincy/stylelint-config': ^2.2.0
    '@unocss/eslint-config': ^66.5.12
    eslint: ^9.39.2
    eslint-plugin-format: ^1.3.0
    lint-staged: ^16.2.7

  nuxt:
    '@element-plus/nuxt': ^1.1.4
    '@nuxt/image': ^2.0.0
    '@nuxt/kit': ^4.2.2
    '@nuxtjs/color-mode': ^4.0.0
    '@pinia/nuxt': ^0.11.3
    '@unocss/nuxt': ^66.5.12
    '@vite-pwa/nuxt': ^1.1.0
    '@vue-macros/nuxt': ^3.1.2
    '@vueuse/nuxt': ^14.1.0
    nuxt: ^4.2.2
  prod:
    '@lincy/async-validation': ^1.4.0
    '@lincy/utils': ^0.7.3
    '@tato30/vue-pdf': ^1.11.5
    better-sqlite3: ^12.6.0
    element-plus: ^2.13.1
    markdown-it-link-attributes: ^4.0.1
    md-editor-v3: ^6.3.1
    md5: ^2.3.0
    pinia: ^3.0.4
    store2: ^2.14.4
  types:
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/md5': ^2.3.6
    '@types/mockjs': ^1.0.10

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - vue-demi

strictPeerDependencies: false
